### ISSUE TITLE
Fails without the Atomix framework

### ISSUE THREAD

**Issue by noahp** [axiomatic-systems/BlueTune#2]
This can't be built standalone, but requires this framework:
https://github.com/axiomatic-systems/Atomix

Pulling the full kit from here works properly though: https://github.com/axiomatic-systems/BlueTuneKit

**Comment by barbibulle** [comment]
Indeed, there are dependencies on 4 frameworks:
Atomix, Neptune, Bento4 and Melo.
Mostly for historical reasons, those are not submodules for the BlueTune repo, but instead there is the BlueTuneKit repo that pulls everything together side by side.

**Comment by noahp** [comment]
Ah, makes sense, thanks!
